language: ruby
sudo: false
services:
  - postgresql
rvm:
  - 2.4.2
branches:
  only:
    - master
before_script:
  - psql -c 'create database granite_ci_test;' -U postgres
  - cp spec/support/database.yml.travis spec/support/database.yml
script:
  - bundle exec rspec
  - bundle exec rubocop
